name: ${name}
main: ${package}.${name}
version: ${version}
author: KaiNoMood

commands:
   betterontime:
      description: BetterOntime command
      aliases: [ontime,bot]
   msgraw:
      description: Send to player a raw private msg

permissions:
    betterontime.log:
        description: Users with this permission will get his time counted
        default: false
    betterontime.self:
        description: Users with this permission can check their ontime
        default: false
    betterontime.leaderboard:
        description: Users with this permission can check the leaderboard
        default: false
    betterontime.others:
        description: Users with this permission can check others ontime
        default: op
    betterontime.manage:
        description: OP-level commands
        default: op
